before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/oldthreefeng/mycli/cmd.Version={{.Version}} -X github.com/oldthreefeng/mycli/cmd.Githash={{.ShortCommit}} -X github.com/oldthreefeng/mycli/cmd.Buildstamp={{.Date}} -X github.com/oldthreefeng/mycli/cmd.Author=goreleaser
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      arm64: aarch64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux

    goarch: amd64

    binaries:
      - mycli

    image_templates:
      - "louisehong/{{.ProjectName}}:latest"
      - "louisehong/{{.ProjectName}}:{{.Tag}}"

    dockerfile: Dockerfile