# syntax=docker/dockerfile:1.0-experimental
FROM alpine:latest
MAINTAINER "louisehong <louisehong4168@gmail.com>"
ARG TARGETPLATFORM
RUN apk update \
    && apk upgrade \
    && apk add --no-cache
     bash \
     jq \
     bash-completion \
     curl \
     wget


ENTRYPOINT ["/usr/bin/mycli"]

WORKDIR /usr/bin/

RUN --mount=target=/build tar xf /build/dist/mycli_*_$(echo ${TARGETPLATFORM} | tr '/' '_' | sed -e 's/arm_/arm/').tar.gz

CMD ["--help"]